name: flutter_annotation_http
description: A new Flutter project.
version: 0.1.0
homepage: https://github.com/wkcdeie/flutter_annotation.git
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  async: ^2.11.0
  http: ^1.1.0
  path: ^1.8.3
  mime: ^1.0.4
  http_parser: ^4.0.2
