name: flutter_annotation_sqlite
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  sqflite_common: ^2.4.5

dev_dependencies:
  test: any
  flutter_lints: ^2.0.0
