name: flutter_annotation_sqlite
description: A new Flutter project.
version: 0.1.0
homepage: https://github.com/wkcdeie/flutter_annotation.git
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sqflite_common: ^2.5.3
