name: flutter_cache_generator
description: Annotation-based JSON serialization, configuration file reading, http requests, routing tool library.
version: 0.0.1
homepage: https://github.com/wkcdeie/flutter_annotation.git
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  code_builder: ^4.5.0
  source_gen: ^1.3.0
  build: ^2.3.0
  analyzer: ^5.13.0
  path: ^1.8.0
  dart_style: ^2.3.0
  flutter_annotation_common:
    path: ../common
  flutter_annotation_cache:
    path: ../cache
