name: flutter_annotation_configure
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  synchronized: ^3.1.0
  flutter_annotation_common:
    path: ../common

dev_dependencies:
  test: any
  flutter_lints: ^2.0.0
